version: "3.9"

volumes:
  data:

services:
  #api:
    #build: .
    #command: npm start
    #ports: 
     # - "3000:3000"
    #volumes: 
     # - .:/usr/app
    #networks: 
     # - postgres-network
    #container_name: "api"
  
  postgresql:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "j81073880"
    ports: 
      - "15432:5432"
    volumes: 
      - data:/var/lib/postgresql/data
    networks: 
      - postgres-network
    container_name: "pgsql"
  
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "jordansilva102@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "j81073880"
    ports: 
      - "16543:80"
    depends_on: 
      - postgresql
    networks: 
      - postgres-network

networks: 
  postgres-network:
    driver: bridge